// VS Code's Modern themes: the standalone defaults, and the palettes VS Code webviews use when
// the Containerlab color scheme overrides the editor theme.
import {
  DARK_VARS,
  VSCODE_DARK_ANSI,
  VSCODE_LIGHT_ANSI,
  terminalAnsiVars,
  type VarMap
} from "./devTheme";

const FONT_VARS: VarMap = {
  "--vscode-font-family": DARK_VARS["--vscode-font-family"],
  "--vscode-font-size": DARK_VARS["--vscode-font-size"]
};

// VS Code "Dark Modern", with the defaults it inherits from Dark+ filled in.
export const DARK_MODERN_VARS: VarMap = {
  "--vscode-editor-background": "#1f1f1f",
  "--vscode-editor-foreground": "#cccccc",
  "--vscode-sideBar-background": "#181818",
  "--vscode-sideBar-foreground": "#cccccc",
  "--vscode-panel-background": "#181818",
  "--vscode-panel-border": "#2b2b2b",
  "--vscode-button-background": "#0078d4",
  "--vscode-button-foreground": "#ffffff",
  "--vscode-button-hoverBackground": "#026ec1",
  "--vscode-button-secondaryBackground": "#313131",
  "--vscode-button-secondaryForeground": "#cccccc",
  "--vscode-button-secondaryHoverBackground": "#3c3c3c",
  "--vscode-input-background": "#313131",
  "--vscode-input-foreground": "#cccccc",
  "--vscode-input-border": "#3c3c3c",
  "--vscode-input-placeholderForeground": "#989898",
  "--vscode-dropdown-background": "#313131",
  "--vscode-dropdown-foreground": "#cccccc",
  "--vscode-dropdown-border": "#3c3c3c",
  "--vscode-focusBorder": "#0078d4",
  "--vscode-foreground": "#cccccc",
  "--vscode-descriptionForeground": "#9d9d9d",
  "--vscode-errorForeground": "#f85149",
  "--vscode-icon-foreground": "#cccccc",
  "--vscode-list-hoverBackground": "#2a2d2e",
  "--vscode-list-activeSelectionBackground": "#04395e",
  "--vscode-list-activeSelectionForeground": "#ffffff",
  "--vscode-list-inactiveSelectionBackground": "#37373d",
  "--vscode-list-inactiveSelectionForeground": "#cccccc",
  "--vscode-badge-background": "#616161",
  "--vscode-badge-foreground": "#f8f8f8",
  "--vscode-scrollbarSlider-background": "rgba(121, 121, 121, 0.4)",
  "--vscode-scrollbarSlider-hoverBackground": "rgba(100, 100, 100, 0.7)",
  "--vscode-scrollbarSlider-activeBackground": "rgba(191, 191, 191, 0.4)",
  "--vscode-statusBar-background": "#181818",
  "--vscode-statusBar-foreground": "#cccccc",
  "--vscode-tab-activeBackground": "#1f1f1f",
  "--vscode-tab-activeForeground": "#ffffff",
  "--vscode-tab-inactiveBackground": "#181818",
  "--vscode-tab-inactiveForeground": "#9d9d9d",
  "--vscode-tab-activeBorderTop": "#0078d4",
  "--vscode-tab-hoverBackground": "#1f1f1f",
  "--vscode-textLink-foreground": "#4daafc",
  "--vscode-textLink-activeForeground": "#4daafc",
  "--vscode-textCodeBlock-background": "#2b2b2b",
  "--vscode-settings-textInputBackground": "#313131",
  "--vscode-settings-textInputForeground": "#cccccc",
  "--vscode-settings-textInputBorder": "#3c3c3c",
  "--vscode-notifications-background": "#1f1f1f",
  "--vscode-notifications-foreground": "#cccccc",
  "--vscode-notifications-border": "#2b2b2b",
  "--vscode-disabledForeground": "rgba(204, 204, 204, 0.5)",
  "--vscode-checkbox-border": "#6b6b6b",
  "--vscode-editorWidget-background": "#202020",
  "--vscode-editorWidget-foreground": "#cccccc",
  "--vscode-editorWidget-border": "#313131",
  "--vscode-widget-shadow": "rgba(0, 0, 0, 0.36)",
  "--vscode-menu-background": "#1f1f1f",
  "--vscode-menu-foreground": "#cccccc",
  "--vscode-menu-border": "#454545",
  "--vscode-menu-selectionBackground": "#0078d4",
  "--vscode-menu-selectionForeground": "#ffffff",
  "--vscode-inputValidation-errorBackground": "#5a1d1d",
  "--vscode-inputValidation-errorBorder": "#be1100",
  "--vscode-inputValidation-errorForeground": "#ffffff",
  "--vscode-inputValidation-warningBackground": "#352a05",
  "--vscode-inputValidation-warningBorder": "#b89500",
  "--vscode-inputValidation-warningForeground": "#ffffff",
  "--vscode-inputValidation-infoBackground": "#063b49",
  "--vscode-inputValidation-infoBorder": "#007acc",
  "--vscode-inputValidation-infoForeground": "#ffffff",
  "--vscode-editorError-foreground": "#f14c4c",
  "--vscode-editorWarning-foreground": "#cca700",
  "--vscode-editorInfo-foreground": "#3794ff",
  "--vscode-charts-yellow": "#cca700",
  "--vscode-testing-iconPassed": "#73c991",
  "--vscode-charts-green": "#89d185",
  "--vscode-progressBar-background": "#0078d4",
  "--vscode-editor-selectionBackground": "#264f78",
  "--vscode-editor-inactiveSelectionBackground": "#3a3d41",
  "--vscode-terminal-selectionBackground": "#264f78",
  ...terminalAnsiVars(VSCODE_DARK_ANSI),
  ...FONT_VARS
};

// VS Code "Light Modern", with the defaults it inherits from Light+ filled in.
export const LIGHT_MODERN_VARS: VarMap = {
  "--vscode-editor-background": "#ffffff",
  "--vscode-editor-foreground": "#3b3b3b",
  "--vscode-sideBar-background": "#f8f8f8",
  "--vscode-sideBar-foreground": "#3b3b3b",
  "--vscode-panel-background": "#f8f8f8",
  "--vscode-panel-border": "#e5e5e5",
  "--vscode-button-background": "#005fb8",
  "--vscode-button-foreground": "#ffffff",
  "--vscode-button-hoverBackground": "#0258a8",
  "--vscode-button-secondaryBackground": "#e5e5e5",
  "--vscode-button-secondaryForeground": "#3b3b3b",
  "--vscode-button-secondaryHoverBackground": "#cccccc",
  "--vscode-input-background": "#ffffff",
  "--vscode-input-foreground": "#3b3b3b",
  "--vscode-input-border": "#cecece",
  "--vscode-input-placeholderForeground": "#767676",
  "--vscode-dropdown-background": "#ffffff",
  "--vscode-dropdown-foreground": "#3b3b3b",
  "--vscode-dropdown-border": "#cecece",
  "--vscode-focusBorder": "#005fb8",
  "--vscode-foreground": "#3b3b3b",
  // Light Modern uses the body color here; a step lighter keeps secondary text distinct.
  "--vscode-descriptionForeground": "#616161",
  "--vscode-errorForeground": "#f85149",
  "--vscode-icon-foreground": "#3b3b3b",
  "--vscode-list-hoverBackground": "#f2f2f2",
  "--vscode-list-activeSelectionBackground": "#e8e8e8",
  "--vscode-list-activeSelectionForeground": "#000000",
  "--vscode-list-inactiveSelectionBackground": "#e4e6f1",
  "--vscode-list-inactiveSelectionForeground": "#3b3b3b",
  "--vscode-badge-background": "#cccccc",
  "--vscode-badge-foreground": "#3b3b3b",
  "--vscode-scrollbarSlider-background": "rgba(100, 100, 100, 0.4)",
  "--vscode-scrollbarSlider-hoverBackground": "rgba(100, 100, 100, 0.7)",
  "--vscode-scrollbarSlider-activeBackground": "rgba(0, 0, 0, 0.6)",
  "--vscode-statusBar-background": "#f8f8f8",
  "--vscode-statusBar-foreground": "#3b3b3b",
  "--vscode-tab-activeBackground": "#ffffff",
  "--vscode-tab-activeForeground": "#3b3b3b",
  "--vscode-tab-inactiveBackground": "#f8f8f8",
  "--vscode-tab-inactiveForeground": "#868686",
  "--vscode-tab-activeBorderTop": "#005fb8",
  "--vscode-tab-hoverBackground": "#ffffff",
  "--vscode-textLink-foreground": "#005fb8",
  "--vscode-textLink-activeForeground": "#005fb8",
  "--vscode-textCodeBlock-background": "#f8f8f8",
  "--vscode-settings-textInputBackground": "#ffffff",
  "--vscode-settings-textInputForeground": "#3b3b3b",
  "--vscode-settings-textInputBorder": "#cecece",
  "--vscode-notifications-background": "#ffffff",
  "--vscode-notifications-foreground": "#3b3b3b",
  "--vscode-notifications-border": "#e5e5e5",
  "--vscode-disabledForeground": "rgba(97, 97, 97, 0.5)",
  "--vscode-checkbox-border": "#8c8c8c",
  "--vscode-editorWidget-background": "#f8f8f8",
  "--vscode-editorWidget-foreground": "#3b3b3b",
  "--vscode-editorWidget-border": "#e5e5e5",
  "--vscode-widget-shadow": "rgba(0, 0, 0, 0.16)",
  "--vscode-menu-background": "#ffffff",
  "--vscode-menu-foreground": "#3b3b3b",
  "--vscode-menu-border": "#cecece",
  "--vscode-menu-selectionBackground": "#005fb8",
  "--vscode-menu-selectionForeground": "#ffffff",
  "--vscode-inputValidation-errorBackground": "#f2dede",
  "--vscode-inputValidation-errorBorder": "#be1100",
  "--vscode-inputValidation-errorForeground": "#3b3b3b",
  "--vscode-inputValidation-warningBackground": "#f6f5d2",
  "--vscode-inputValidation-warningBorder": "#bf8803",
  "--vscode-inputValidation-warningForeground": "#3b3b3b",
  "--vscode-inputValidation-infoBackground": "#d6ecf2",
  "--vscode-inputValidation-infoBorder": "#007acc",
  "--vscode-inputValidation-infoForeground": "#3b3b3b",
  "--vscode-editorError-foreground": "#e51400",
  "--vscode-editorWarning-foreground": "#bf8803",
  "--vscode-editorInfo-foreground": "#1a85ff",
  "--vscode-charts-yellow": "#bf8803",
  "--vscode-testing-iconPassed": "#388a34",
  "--vscode-charts-green": "#388a34",
  "--vscode-progressBar-background": "#005fb8",
  "--vscode-editor-selectionBackground": "#add6ff",
  "--vscode-editor-inactiveSelectionBackground": "#e5ebf1",
  "--vscode-terminal-selectionBackground": "#add6ff",
  ...terminalAnsiVars(VSCODE_LIGHT_ANSI),
  ...FONT_VARS
};
