/**
 * annotationUIStore - Zustand store for annotation UI state
 *
 * This store manages annotation-specific UI state like selections and editing.
 * Annotation data is derived from graphStore via useDerivedAnnotations hook.
 *
 * The four annotation kinds (groups / text / shapes / traffic-rate) share the
 * same selection and editor mechanics, so their actions are generated by small
 * factories instead of being copy-pasted per kind.
 */
import { createWithEqualityFn } from "zustand/traditional";
import { shallow } from "zustand/shallow";
import type { StoreApi } from "zustand";

import type {
  FreeTextAnnotation,
  FreeShapeAnnotation,
  TrafficRateAnnotation
} from "../core/types/topology";
import type { GroupEditorData } from "../hooks/canvas/groupTypes";

// ============================================================================
// Types
// ============================================================================

type ShapeAnnotationType = FreeShapeAnnotation["shapeType"];

export interface AnnotationUIState {
  // Group UI state
  selectedGroupIds: Set<string>;
  editingGroup: GroupEditorData | null;

  // Text annotation UI state
  selectedTextIds: Set<string>;
  editingTextAnnotation: FreeTextAnnotation | null;
  /** Text annotation currently being edited inline on the canvas */
  inlineEditingTextId: string | null;
  isAddTextMode: boolean;

  // Shape annotation UI state
  selectedShapeIds: Set<string>;
  editingShapeAnnotation: FreeShapeAnnotation | null;
  isAddShapeMode: boolean;
  pendingShapeType: ShapeAnnotationType;

  // Traffic-rate annotation UI state
  selectedTrafficRateIds: Set<string>;
  editingTrafficRateAnnotation: TrafficRateAnnotation | null;
}

export interface AnnotationUIActions {
  // Group selection
  selectGroup: (id: string) => void;
  toggleGroupSelection: (id: string) => void;
  boxSelectGroups: (ids: string[]) => void;
  clearGroupSelection: () => void;

  // Group editing
  setEditingGroup: (data: GroupEditorData | null) => void;
  closeGroupEditor: () => void;

  // Text annotation selection
  selectTextAnnotation: (id: string) => void;
  toggleTextAnnotationSelection: (id: string) => void;
  boxSelectTextAnnotations: (ids: string[]) => void;
  clearTextAnnotationSelection: () => void;

  // Text annotation editing
  setEditingTextAnnotation: (annotation: FreeTextAnnotation | null) => void;
  closeTextEditor: () => void;
  setInlineEditingTextId: (id: string | null) => void;
  setAddTextMode: (enabled: boolean) => void;
  disableAddTextMode: () => void;

  // Shape annotation selection
  selectShapeAnnotation: (id: string) => void;
  toggleShapeAnnotationSelection: (id: string) => void;
  boxSelectShapeAnnotations: (ids: string[]) => void;
  clearShapeAnnotationSelection: () => void;

  // Shape annotation editing
  setEditingShapeAnnotation: (annotation: FreeShapeAnnotation | null) => void;
  closeShapeEditor: () => void;
  setAddShapeMode: (enabled: boolean, shapeType?: ShapeAnnotationType) => void;
  disableAddShapeMode: () => void;
  setPendingShapeType: (shapeType: ShapeAnnotationType) => void;

  // Traffic-rate annotation selection
  selectTrafficRateAnnotation: (id: string) => void;
  toggleTrafficRateAnnotationSelection: (id: string) => void;
  boxSelectTrafficRateAnnotations: (ids: string[]) => void;
  clearTrafficRateAnnotationSelection: () => void;

  // Traffic-rate annotation editing
  setEditingTrafficRateAnnotation: (annotation: TrafficRateAnnotation | null) => void;
  closeTrafficRateEditor: () => void;

  // Utility
  clearAllSelections: () => void;

  // For deletion cleanup
  removeFromGroupSelection: (id: string) => void;
  removeFromTextSelection: (id: string) => void;
  removeFromShapeSelection: (id: string) => void;
  removeFromTrafficRateSelection: (id: string) => void;
}

export type AnnotationUIStore = AnnotationUIState & AnnotationUIActions;

// ============================================================================
// Initial State
// ============================================================================

const initialState: AnnotationUIState = {
  selectedGroupIds: new Set(),
  editingGroup: null,
  selectedTextIds: new Set(),
  editingTextAnnotation: null,
  inlineEditingTextId: null,
  isAddTextMode: false,
  selectedShapeIds: new Set(),
  editingShapeAnnotation: null,
  isAddShapeMode: false,
  pendingShapeType: "rectangle",
  selectedTrafficRateIds: new Set(),
  editingTrafficRateAnnotation: null
};

// ============================================================================
// Per-Kind Action Factories
// ============================================================================

type SetState = StoreApi<AnnotationUIStore>["setState"];

type SelectionKey =
  | "selectedGroupIds"
  | "selectedTextIds"
  | "selectedShapeIds"
  | "selectedTrafficRateIds";

/** Selection actions for one Set<string>-based selection slice. */
function createSelectionActions(set: SetState, key: SelectionKey) {
  const write = (ids: Set<string>) => {
    const patch: Partial<AnnotationUIState> = {};
    patch[key] = ids;
    set(patch);
  };
  return {
    select: (id: string) => {
      write(new Set([id]));
    },
    toggle: (id: string) => {
      set((state) => {
        const next = new Set(state[key]);
        if (next.has(id)) next.delete(id);
        else next.add(id);
        const patch: Partial<AnnotationUIState> = {};
        patch[key] = next;
        return patch;
      });
    },
    boxSelect: (ids: string[]) => {
      write(new Set(ids));
    },
    clear: () => {
      write(new Set());
    },
    removeFrom: (id: string) => {
      set((state) => {
        if (!state[key].has(id)) return state;
        const next = new Set(state[key]);
        next.delete(id);
        const patch: Partial<AnnotationUIState> = {};
        patch[key] = next;
        return patch;
      });
    }
  };
}

type EditorKey =
  | "editingGroup"
  | "editingTextAnnotation"
  | "editingShapeAnnotation"
  | "editingTrafficRateAnnotation";

/** Patch that closes every annotation editor. */
const ALL_EDITORS_CLOSED: Pick<AnnotationUIState, EditorKey> = {
  editingGroup: null,
  editingTextAnnotation: null,
  editingShapeAnnotation: null,
  editingTrafficRateAnnotation: null
};

/** Editor open/close actions for one annotation kind. */
function createEditorActions<K extends EditorKey>(set: SetState, key: K) {
  const setEditing = (value: AnnotationUIState[K] | null) => {
    // Ensure only one annotation editor is active at a time: opening an editor
    // closes all others. Closing (value === null) only clears this editor.
    const patch: Partial<AnnotationUIState> = value ? { ...ALL_EDITORS_CLOSED } : {};
    patch[key] = value as AnnotationUIState[K];
    set(patch);
  };
  return {
    setEditing,
    close: () => {
      setEditing(null);
    }
  };
}

// ============================================================================
// Store Creation
// ============================================================================

export const useAnnotationUIStore = createWithEqualityFn<AnnotationUIStore>((set) => {
  const groupSelection = createSelectionActions(set, "selectedGroupIds");
  const textSelection = createSelectionActions(set, "selectedTextIds");
  const shapeSelection = createSelectionActions(set, "selectedShapeIds");
  const trafficRateSelection = createSelectionActions(set, "selectedTrafficRateIds");

  const groupEditor = createEditorActions(set, "editingGroup");
  const textEditor = createEditorActions(set, "editingTextAnnotation");
  const shapeEditor = createEditorActions(set, "editingShapeAnnotation");
  const trafficRateEditor = createEditorActions(set, "editingTrafficRateAnnotation");

  return {
    ...initialState,

    // Group selection + editing
    selectGroup: groupSelection.select,
    toggleGroupSelection: groupSelection.toggle,
    boxSelectGroups: groupSelection.boxSelect,
    clearGroupSelection: groupSelection.clear,
    setEditingGroup: groupEditor.setEditing,
    closeGroupEditor: groupEditor.close,

    // Text annotation selection + editing
    selectTextAnnotation: textSelection.select,
    toggleTextAnnotationSelection: textSelection.toggle,
    boxSelectTextAnnotations: textSelection.boxSelect,
    clearTextAnnotationSelection: textSelection.clear,
    setEditingTextAnnotation: textEditor.setEditing,
    closeTextEditor: textEditor.close,
    setInlineEditingTextId: (inlineEditingTextId) => {
      set({ inlineEditingTextId });
    },
    setAddTextMode: (isAddTextMode) => {
      // Add-text and add-shape modes are mutually exclusive.
      set({ isAddTextMode, isAddShapeMode: false });
    },
    disableAddTextMode: () => {
      set({ isAddTextMode: false });
    },

    // Shape annotation selection + editing
    selectShapeAnnotation: shapeSelection.select,
    toggleShapeAnnotationSelection: shapeSelection.toggle,
    boxSelectShapeAnnotations: shapeSelection.boxSelect,
    clearShapeAnnotationSelection: shapeSelection.clear,
    setEditingShapeAnnotation: shapeEditor.setEditing,
    closeShapeEditor: shapeEditor.close,
    setAddShapeMode: (enabled, shapeType) => {
      set({
        isAddShapeMode: enabled,
        isAddTextMode: false,
        ...(shapeType ? { pendingShapeType: shapeType } : {})
      });
    },
    disableAddShapeMode: () => {
      set({ isAddShapeMode: false });
    },
    setPendingShapeType: (pendingShapeType) => {
      set({ pendingShapeType });
    },

    // Traffic-rate annotation selection + editing
    selectTrafficRateAnnotation: trafficRateSelection.select,
    toggleTrafficRateAnnotationSelection: trafficRateSelection.toggle,
    boxSelectTrafficRateAnnotations: trafficRateSelection.boxSelect,
    clearTrafficRateAnnotationSelection: trafficRateSelection.clear,
    setEditingTrafficRateAnnotation: trafficRateEditor.setEditing,
    closeTrafficRateEditor: trafficRateEditor.close,

    // Utility
    clearAllSelections: () => {
      set({
        selectedGroupIds: new Set(),
        selectedTextIds: new Set(),
        selectedShapeIds: new Set(),
        selectedTrafficRateIds: new Set()
      });
    },

    // For deletion cleanup
    removeFromGroupSelection: groupSelection.removeFrom,
    removeFromTextSelection: textSelection.removeFrom,
    removeFromShapeSelection: shapeSelection.removeFrom,
    removeFromTrafficRateSelection: trafficRateSelection.removeFrom
  };
});

// ============================================================================
// Selector Hooks (for convenience)
// ============================================================================

/** Get annotation UI state (group/text/shape selections and edit modes) */
export const useAnnotationUIState = () =>
  useAnnotationUIStore(
    (state) => ({
      selectedGroupIds: state.selectedGroupIds,
      editingGroup: state.editingGroup,
      selectedTextIds: state.selectedTextIds,
      editingTextAnnotation: state.editingTextAnnotation,
      inlineEditingTextId: state.inlineEditingTextId,
      isAddTextMode: state.isAddTextMode,
      selectedShapeIds: state.selectedShapeIds,
      editingShapeAnnotation: state.editingShapeAnnotation,
      isAddShapeMode: state.isAddShapeMode,
      pendingShapeType: state.pendingShapeType,
      selectedTrafficRateIds: state.selectedTrafficRateIds,
      editingTrafficRateAnnotation: state.editingTrafficRateAnnotation
    }),
    shallow
  );

/** Get annotation UI actions (stable) */
export const useAnnotationUIActions = () =>
  useAnnotationUIStore(
    (state) => ({
      selectGroup: state.selectGroup,
      toggleGroupSelection: state.toggleGroupSelection,
      boxSelectGroups: state.boxSelectGroups,
      clearGroupSelection: state.clearGroupSelection,
      setEditingGroup: state.setEditingGroup,
      closeGroupEditor: state.closeGroupEditor,
      selectTextAnnotation: state.selectTextAnnotation,
      toggleTextAnnotationSelection: state.toggleTextAnnotationSelection,
      boxSelectTextAnnotations: state.boxSelectTextAnnotations,
      clearTextAnnotationSelection: state.clearTextAnnotationSelection,
      setEditingTextAnnotation: state.setEditingTextAnnotation,
      closeTextEditor: state.closeTextEditor,
      setInlineEditingTextId: state.setInlineEditingTextId,
      setAddTextMode: state.setAddTextMode,
      disableAddTextMode: state.disableAddTextMode,
      selectShapeAnnotation: state.selectShapeAnnotation,
      toggleShapeAnnotationSelection: state.toggleShapeAnnotationSelection,
      boxSelectShapeAnnotations: state.boxSelectShapeAnnotations,
      clearShapeAnnotationSelection: state.clearShapeAnnotationSelection,
      setEditingShapeAnnotation: state.setEditingShapeAnnotation,
      closeShapeEditor: state.closeShapeEditor,
      setAddShapeMode: state.setAddShapeMode,
      disableAddShapeMode: state.disableAddShapeMode,
      setPendingShapeType: state.setPendingShapeType,
      selectTrafficRateAnnotation: state.selectTrafficRateAnnotation,
      toggleTrafficRateAnnotationSelection: state.toggleTrafficRateAnnotationSelection,
      boxSelectTrafficRateAnnotations: state.boxSelectTrafficRateAnnotations,
      clearTrafficRateAnnotationSelection: state.clearTrafficRateAnnotationSelection,
      setEditingTrafficRateAnnotation: state.setEditingTrafficRateAnnotation,
      closeTrafficRateEditor: state.closeTrafficRateEditor,
      clearAllSelections: state.clearAllSelections,
      removeFromGroupSelection: state.removeFromGroupSelection,
      removeFromTextSelection: state.removeFromTextSelection,
      removeFromShapeSelection: state.removeFromShapeSelection,
      removeFromTrafficRateSelection: state.removeFromTrafficRateSelection
    }),
    shallow
  );
